drop table official;
drop table court;
drop table player;

/* Creating tables */
create table OFFICIAL
(No integer not null primary key,
 Name varchar(30) not null,
 Country varchar(20) not null,
 gender char(1) not null);

create table PLAYER
(Id integer not null primary key,
 Name varchar(25) not null,
 Country varchar(25) not null,
 SeedNo integer check (SeedNo between 1 and 32));

/* Adding data into the OFFICIAL table */
insert into OFFICIAL values(1,'Dick Braco','Trinidad and Tobago','m');
insert into OFFICIAL values(2,'Piers Palmer','UK','m');
insert into OFFICIAL values(3,'Gerry Armstrong','UK','m');
insert into OFFICIAL values(4,'Sav Loizou','UK','m');
insert into OFFICIAL values(5,'Nicholas Rodotheos Panayi','UK','m');
insert into OFFICIAL values(6,'Toby Granger','UK','m');
insert into OFFICIAL values(7,'James Keothavong','UK','m');
insert into OFFICIAL values(8,'Mario Yiddo Kitibos','Uzbekistan','m');
insert into OFFICIAL values(9,'Carlos Bernardes','Brazil','m');
insert into OFFICIAL values(10,'Mohamed El Jennati','Morocco','m');
insert into OFFICIAL values(11,'Jake Garner','USA','m');
insert into OFFICIAL values(12,'Lars Graff','Sweden','m');
insert into OFFICIAL values(13,'Roland Herfel','Germany','m');
insert into OFFICIAL values(14,'Emmanuel Joseph','France','m');
insert into OFFICIAL values(15,'Mohamed Lahyani ','Sweden','m');
insert into OFFICIAL values(16,'Pascal Maria','France','m');
insert into OFFICIAL values(17,'Gianluca Moscarella','Italy','m');
insert into OFFICIAL values(18,'Cedric Mourier','France','m');
insert into OFFICIAL values(19,'Fergus Murphy','Ireland','m');
insert into OFFICIAL values(20,'Ali Nili','Iran','m');
insert into OFFICIAL values(21,'Kader Nouni','France','m');
insert into OFFICIAL values(22,'Carlos Ramos','Portugal','m');
insert into OFFICIAL values(23,'Damina Steiner','Argentina','m');
insert into OFFICIAL values(24,'Andreas Egli','Switzerland','m');
insert into OFFICIAL values(25,'Anne Lasserre Ullrich','France','f');
insert into OFFICIAL values(26,'Bertie Bowron','UK','m');
insert into OFFICIAL values(27,'Bruno Rebeuh','France','m');
insert into OFFICIAL values(28,'Cecil Hollins','USA','m');
insert into OFFICIAL values(29,'Christina Olaussen','Denmark','f');
insert into OFFICIAL values(30,'David Littlefield','USA','m');
insert into OFFICIAL values(31,'Enric Molina','Spain','m');
insert into OFFICIAL values(32,'Denis Overberg','Australia','m');
insert into OFFICIAL values(33,'Donna Kelso','Australia','f');
insert into OFFICIAL values(34,'Edward James','UK','m');
insert into OFFICIAL values(35,'Fabian Cherny','Argentina','m');
insert into OFFICIAL values(36,'Fiona Edwards','UK','f');
insert into OFFICIAL values(37,'Frank Hammond','USA','m');
insert into OFFICIAL values(38,'Freddie Sore','UK','m');
insert into OFFICIAL values(39,'Georgina Clark','UK','f');
insert into OFFICIAL values(40,'Gil de Kermadec','France','m');
insert into OFFICIAL values(41,'Jane Harvey','UK','f');
insert into OFFICIAL values(42,'Javier Moreno','Spain','m');
insert into OFFICIAL values(43,'Jeremy Shales','UK','m');
insert into OFFICIAL values(44,'John Frame','UK','m');
insert into OFFICIAL values(45,'John Parry','UK','m');
insert into OFFICIAL values(46,'Jorge Dias','Portugal','m');
insert into OFFICIAL values(47,'Kerrilyn Cramer','Australia','f');
insert into OFFICIAL values(48,'Laura Ceccarelli','Italy','f');
insert into OFFICIAL values(49,'Leanne White','Australia','f');
insert into OFFICIAL values(50,'Lynn Welch','USA','f');
insert into OFFICIAL values(51,'Mike Morrissey','UK','m');
insert into OFFICIAL values(52,'Norbert Peick','Germany','m');
insert into OFFICIAL values(53,'Norm Chryst','USA','m');
insert into OFFICIAL values(54,'Richard Ings','Australia','m');
insert into OFFICIAL values(55,'Romano Grillotti','Italy','m');
insert into OFFICIAL values(56,'Sandra de Jenken','France','f');
insert into OFFICIAL values(57,'Steve Ullrich','USA','m');
insert into OFFICIAL values(58,'Ted Watts','UK','m');
insert into OFFICIAL values(59,'Sylvia Watts','UK','f');
insert into OFFICIAL values(60,'Wayne McKewen','Australia','m');
insert into OFFICIAL values(61,'Missy Malool','USA','f');
insert into OFFICIAL values(62,'Bunny Williams','USA','f');
insert into OFFICIAL values(63,'Billy Lipp','USA','m');
insert into OFFICIAL values(64,'Dessie Samuels','USA','f');
insert into OFFICIAL values(65,'Mike Loo','USA','m');
insert into OFFICIAL values(66,'Kieth Crossland','USA','m');


/* Adding data into the PLAYER table */
insert into PLAYER values(1,'Novak Djokovic','Serbia',1);
insert into PLAYER values(2,'Philipp Kohlschreiber','Germany',null);
insert into PLAYER values(3,'Jarkko Nieminen','Finland',null);
insert into PLAYER values(4,'Lleyton Hewitt ','Australia',null);
insert into PLAYER values(5,'Pierre-Hugues Herbert','France',null);
insert into PLAYER values(6,'Hyeon Chung','Korea',null);
insert into PLAYER values(7,'Jan-Lennard Struff','Germany',null);
insert into PLAYER values(8,'Bernard Tomic','Australia',27);
insert into PLAYER values(9,'Leonardo Mayer','Argentina',24);
insert into PLAYER values(10,'Thanasi Kokkinakis','Australia',null);
insert into PLAYER values(11,'Janko Tipsarevic','Serbia',null);
insert into PLAYER values(12,'Marcel Granollers','Spain',null);
insert into PLAYER values(13,'Marsel Ilhan','Turkey',null);
insert into PLAYER values(14,'Jerzy Janowicz','Poland',null);
insert into PLAYER values(15,'Lucas Pouille','France',null);
insert into PLAYER values(16,'Kevin Anderson','South Africa',14);
insert into PLAYER values(17,'Marin Cilic','Croatia',9);
insert into PLAYER values(18,'Hiroki Moriya','Japan',null);
insert into PLAYER values(19,'Andreas Haider-Maurer','Austria',null);
insert into PLAYER values(20,'Ricardas Berankis','Lithuania',null);
insert into PLAYER values(21,'Matthew Ebden','Australia',null);
insert into PLAYER values(22,'Blaz Rola','Slovenia',null);
insert into PLAYER values(23,'Go Soeda','Japan',null);
insert into PLAYER values(24,'John Isner','USA',17);
insert into PLAYER values(25,'Pablo Cuevas','Uruguay',28);
insert into PLAYER values(26,'Denis Kudla','USA',null);
insert into PLAYER values(27,'Teymuraz Gabashvili','Russia',null);
insert into PLAYER values(28,'Alexander Zverev','Germany',null);
insert into PLAYER values(29,'Joao Souza','Brazil',null);
insert into PLAYER values(30,'Santiago Giraldo','Colombia',null);
insert into PLAYER values(31,'Simone Bolelli','Italy',null);
insert into PLAYER values(32,'Kei Nishikori','Japan',5);
insert into PLAYER values(33,'Stanislas Wawrinka','Switzerland',4);
insert into PLAYER values(34,'Joao Sousa','Portugal',null);
insert into PLAYER values(35,'Victor Estrella','Dominican Republic',null);
insert into PLAYER values(36,'Benjamin Becker','Germany',null);
insert into PLAYER values(37,'Martin Klizan','Slovakia',null);
insert into PLAYER values(38,'Fernando Verdasco','Spain',null);
insert into PLAYER values(39,'Dudi Sela','Israel',null);
insert into PLAYER values(40,'Dominic Thiem','Austria',32);
insert into PLAYER values(41,'Tommy Robredo','Spain',19);
insert into PLAYER values(42,'John Millman','Australia',null);
insert into PLAYER values(43,'Donald Young','USA',null);
insert into PLAYER values(44,'Marcos Baghdatis','Cyprus',null);
insert into PLAYER values(45,'Liam Broady','UK',null);
insert into PLAYER values(46,'Marinko Matosevic','Australia',null);
insert into PLAYER values(47,'Horacio Zeballos','Argentina',null);
insert into PLAYER values(48,'David Goffin','Belgium',16);
insert into PLAYER values(49,'Grigor Dimitrov','Bulgaria',11);
insert into PLAYER values(50,'Federico Delbonis','Argentina',null);
insert into PLAYER values(51,'Lukas Lacko','Slovakia',null);
insert into PLAYER values(52,'Steve Johnson','USA',null);
insert into PLAYER values(53,'Kenny De Schepper','France',null);
insert into PLAYER values(54,'John-Patrick Smith','Australia',null);
insert into PLAYER values(55,'Luke Saville','Australia',null);
insert into PLAYER values(56,'Richard Gasquet','France',21);
insert into PLAYER values(57,'Nick Kyrgios','Australia',26);
insert into PLAYER values(58,'Diego Schwartzman','Argentina',null);
insert into PLAYER values(59,'Juan Monaco','Argentina',null);
insert into PLAYER values(60,'Florian Mayer','Germany',null);
insert into PLAYER values(61,'Dusan Lajovic','Serbia',null);
insert into PLAYER values(62,'Tommy Haas','Germany',null);
insert into PLAYER values(63,'Daniel Gimeno','Spain',null);
insert into PLAYER values(64,'Milos Raonic','Canada',7);
insert into PLAYER values(65,'Luca Vanni','Italy',null);
insert into PLAYER values(66,'James Ward','UK',null);
insert into PLAYER values(67,'Jiri Vesely','Czech Republic',null);
insert into PLAYER values(68,'Paolo Lorenzi','Italy',null);
insert into PLAYER values(69,'Vasek Pospisil','Canada',null);
insert into PLAYER values(70,'Vincent Millot','France',null);
insert into PLAYER values(71,'Tim Smyczek','USA',null);
insert into PLAYER values(72,'Fabio Fognini','Italy',30);
insert into PLAYER values(73,'Viktor Troicki','Serbia',22);
insert into PLAYER values(74,'Aleksandr Nedovyesov','Kazakhstan',null);
insert into PLAYER values(75,'Radek Stepanek','Czech Republic',null);
insert into PLAYER values(76,'Aljaz Bedene','UK',null);
insert into PLAYER values(77,'Dustin Brown','Germany',null);
insert into PLAYER values(78,'Yen-Hsun Lu','Chinese Taipei',null);
insert into PLAYER values(79,'Thomaz Bellucci','Brazil',null);
insert into PLAYER values(80,'Rafael Nadal','Spain',10);
insert into PLAYER values(81,'Jo-Wilfried Tsonga','France',13);
insert into PLAYER values(82,'Gilles Muller','Luxembourg',null);
insert into PLAYER values(83,'Denis Istomin','Uzbekistan',null);
insert into PLAYER values(84,'Albert Ramos','Spain',null);
insert into PLAYER values(85,'Alexandr Dolgopolov','Ukraine',null);
insert into PLAYER values(86,'Kyle Edmund','UK',null);
insert into PLAYER values(87,'Elias Ymer','Sweden',null);
insert into PLAYER values(88,'Ivo Karlovic','Croatia',23);
insert into PLAYER values(89,'Andreas Seppi','Italy',25);
insert into PLAYER values(90,'Brydan Klein','UK',null);
insert into PLAYER values(91,'Sergiy Stakhovsky','Ukraine',null);
insert into PLAYER values(92,'Borna Coric','Croatia',null);
insert into PLAYER values(93,'Robin Haase','Netherlands',null);
insert into PLAYER values(94,'Alejandro Falla','Colombia',null);
insert into PLAYER values(95,'Mikhail Kukushkin','Kazakhstan',null);
insert into PLAYER values(96,'Andy Murray','UK',3);
insert into PLAYER values(97,'Tomas Berdych','Czech Republic',6);
insert into PLAYER values(98,'Jeremy Chardy','France',null);
insert into PLAYER values(99,'Filip Krajinovic','Serbia',null);
insert into PLAYER values(100,'Nicolas Mahut','France',null);
insert into PLAYER values(101,'Ernests Gulbis','Latvia',null);
insert into PLAYER values(102,'Lukas Rosol','Czech Republic',null);
insert into PLAYER values(103,'Pablo Andujar','Spain',null);
insert into PLAYER values(104,'Guillermo Garcia-Lopez','Spain',29);
insert into PLAYER values(105,'Gael Monfils','France',18);
insert into PLAYER values(106,'Pablo Carreno','Spain',null);
insert into PLAYER values(107,'Adrian Mannarino','France',null);
insert into PLAYER values(108,'Michael Berrer','Germany',null);
insert into PLAYER values(109,'Yuichi Sugita','Japan',null);
insert into PLAYER values(110,'Blaz Kavcic','Slovenia',null);
insert into PLAYER values(111,'Nicolas Almagro','Spain',null);
insert into PLAYER values(112,'Gilles Simon','France',12);
insert into PLAYER values(113,'Feliciano Lopez','Spain',15) ;
insert into PLAYER values(114,'Steve Darcis','Belgium',null);
insert into PLAYER values(115,'Nikoloz Basilashvili','Georgia',null);
insert into PLAYER values(116,'Facundo Bagnis','Argentina',null);
insert into PLAYER values(117,'Benoit Paire','France',null);
insert into PLAYER values(118,'Mikhail Youzhny','Russia',null);
insert into PLAYER values(119,'Ruben Bemelmans','Belgium',null);
insert into PLAYER values(120,'Roberto Bautista','Spain',20);
insert into PLAYER values(121,'Jack Sock','USA',31);
insert into PLAYER values(122,'Samuel Groth','Australia',null);
insert into PLAYER values(123,'Malek Jaziri','Tunisia',null);
insert into PLAYER values(124,'James Duckworth','Australia',null);
insert into PLAYER values(125,'Sam Querrey','USA',null);
insert into PLAYER values(126,'Igor Sijsling','Netherlands',null);
insert into PLAYER values(127,'Damir Dzumhur','Bosnia and Herzegovina',null);
insert into PLAYER values(128,'Roger Federer','Switzerland',2);

